name: Release Addon Zip

on:
  push:
    tags:
      - 'v*.*'

jobs:
  create_release:
    name: Create GitHub Release with Addon Zip
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug file structure
        run: ls -R

      - name: Disable debug mode in modal_window.gd
        run: |
          sed -i 's/var _print_debug := true/var _print_debug := false/' ./addons/modal_window/modal_window.gd

      - name: Create release zip file
        run: |
          cd ./addons
          zip -r ../modal_window.zip ./modal_window
          cd ..

      - name: Verify modal_window.zip
        run: ls -l ./modal_window.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload modal_window.zip to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./modal_window.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
