name: Release Addon Zip

on:
  push:
    tags:
      - 'v*.*'

jobs:
  create_release:
    name: Create GitHub Release with Addon Zip
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug file structure
        run: ls -R

      - name: Create release zip file
        run: |
          VERSION=${{ github.ref_name }}
          mkdir -p ./temp/modal_window_addon_$VERSION
          cp -r ./addons/* ./temp/modal_window_addon_$VERSION/
          cd ./temp
          zip -r ../for_godot_asset_library.zip ./modal_window_addon_$VERSION
          cd ..
          zip -r ./modal_window.zip ./addons/modal_window

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload the zip files to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./modal_window.zip
            ./for_godot_asset_library.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
